/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controler.conexcion;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author mdavi
 */
public class NewUssers extends javax.swing.JInternalFrame {
    
    
    public void ingresar() {

        conexcion db_connect = new conexcion();
        PreparedStatement ps = null;
        String User_name = txtNewUsuario.getText();
        String Passwordss = txtNewPass.getText();
        if (User_name.equals("") || Passwordss.equals("")) {
            JOptionPane.showMessageDialog(this, "!!!Uno o mas campos estan vacios. Favor de llenarlos.");
        } else {
            try ( Connection conexion = db_connect.get_connection()) {
                try {
                    String query = "INSERT INTO usser(user_name,passwordss)VALUES(?,?)";
                    ps = conexion.prepareStatement(query);
                    ps.setString(1, txtNewUsuario.getText());
                    ps.setString(2, txtNewPass.getText());
                    ps.executeUpdate();
                    System.out.println("usuario creado");
                    this.dispose();
                    /*new Systemm().setVisible(true);*/
                    JOptionPane.showMessageDialog(this, "Usuario Creado Exitosamente.");

                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            } catch (SQLException e) {
                System.err.print(e.toString());
                JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado.\nFavor comunicarse con el administrador.");
            }
        }

    }
    
    
    
    
    
    
    
    
    

    /**
     * Creates new form NewUssers
     */
    public NewUssers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNewUsuario = new javax.swing.JTextField();
        btCrearUsuario = new javax.swing.JButton();
        txtNewPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo Usuario");

        txtNewUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewUsuarioKeyTyped(evt);
            }
        });

        btCrearUsuario.setText("Crear");
        btCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCrearUsuarioMouseClicked(evt);
            }
        });
        btCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearUsuarioActionPerformed(evt);
            }
        });

        txtNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewPassKeyTyped(evt);
            }
        });

        jLabel1.setText("Nombre del nuevo Usuario :");

        jLabel2.setText("Password ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtNewUsuario)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btCrearUsuario)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNewUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btCrearUsuario)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewUsuarioKeyTyped
        // TODO add your handling code here:
        if (txtNewUsuario.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNewUsuarioKeyTyped

    private void btCrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCrearUsuarioMouseClicked
        // TODO add your handling code here:
        if (MouseEvent.BUTTON1 == evt.getButton()) {
            ingresar();
        }
    }//GEN-LAST:event_btCrearUsuarioMouseClicked

    private void btCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCrearUsuarioActionPerformed

    private void txtNewPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPassKeyTyped
        // TODO add your handling code here:
        if (txtNewPass.getText().length() == 25) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNewPassKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrearUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JTextField txtNewUsuario;
    // End of variables declaration//GEN-END:variables
}
