/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controler.CTMeasure;
import Controler.conexcion;
import Modelo.measure;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mdavi
 */
public class Productss extends javax.swing.JInternalFrame {

    conexcion con = new conexcion();
    Connection conexcion = con.get_connection();

    public Productss() {
        initComponents();
        cargarMedida(boxMedida);
        showTableProduct();
    }

    public void showTableProduct() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id Product");
        model.addColumn("Producto");
        model.addColumn("Id Measure");
        model.addColumn("Medida");
        model.addColumn("Acrónimo");
        tlProduct.setModel(model);

        String[] datos = new String[5];
        try {

            Statement leer = conexcion.createStatement();
            ResultSet rs = leer.executeQuery("SELECT pr.ID_PRODUCT,pr.NAME_PRODUCT,pr.ID_MEASURE,me.NAME_MEASURE,me.ACRONYM\n"
                    + "FROM product pr JOIN measure me ON pr.ID_MEASURE=me.ID_MEASURE");

            while (rs.next()) {

                System.out.println(rs.getString(1));
                System.out.println(rs.getString(2));
                System.out.println(rs.getString(3));
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                model.addRow(datos);

            }
            tlProduct.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error" + e.toString());
        }
    }

    public void actualizarProducto() {
        int fila = tlProduct.getSelectedRow();
        System.out.println(fila);

        int idProduct = Integer.parseInt(this.tlProduct.getValueAt(fila, 0).toString());
        String namePro = tlProduct.getValueAt(fila, 1).toString();
        String idpreo = tlProduct.getValueAt(fila, 2).toString();

        System.out.println("La cantidad es: " + namePro);
        System.out.println("El precio es : " + idpreo);

        if (namePro.isEmpty() || idpreo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "!!!Campos vacios por favor llenar registros.");
        } else {
            try {
                PreparedStatement actu = conexcion.prepareStatement("UPDATE product SET NAME_PRODUCT ='" + namePro + "', ID_MEASURE=" + idpreo + " WHERE ID_PRODUCT = " + idProduct + "");
                actu.executeUpdate();
                showTableProduct();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error" + e.toString());

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuIProduct = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlProduct = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNameProduct = new javax.swing.JTextPane();
        btGuardarProduct = new javax.swing.JButton();
        boxMedida = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jMenuIProduct.setText("Actualizar Producto");
        jMenuIProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIProductActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuIProduct);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Productos");

        tlProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tlProduct.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tlProduct.setComponentPopupMenu(jPopupMenu1);
        tlProduct.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jScrollPane1.setViewportView(tlProduct);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Productos", jPanel2);

        jScrollPane3.setViewportView(txtNameProduct);

        btGuardarProduct.setText("Guardar Producto");
        btGuardarProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarProductActionPerformed(evt);
            }
        });

        boxMedida.setToolTipText("Seleccione Campo");
        boxMedida.setAutoscrolls(true);
        boxMedida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boxMedida.setDoubleBuffered(true);
        boxMedida.setKeySelectionManager(null);
        boxMedida.setName("Seleccione Campo"); // NOI18N
        boxMedida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxMedidaItemStateChanged(evt);
            }
        });
        boxMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMedidaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del Producto");

        jLabel2.setText("Medida Metrología");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btGuardarProduct)))
                .addContainerGap(202, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(boxMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGuardarProduct))
                .addGap(47, 47, 47)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        boxMedida.getAccessibleContext().setAccessibleName("Seleccione Campo");

        jTabbedPane1.addTab("Nuevo Producto", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarProductActionPerformed
        // TODO add your handling code here:
        //String idMeasure = boxMedida.getItemAt(WIDTH));
        // meus = boxMedida.getItemAt(boxMedida.getSelectedIndex()).getId_measure();

        //int medi;
        //String boxMedi;
        String nameMeasure = txtNameProduct.getText();
        String boxMedi = boxMedida.getSelectedItem().toString();
        //medi = Integer.parseInt(boxMedi);
        //System.out.println("boxMedi   " + boxMedi);
        //System.out.println("medi   " + medi);

        String[] RayMedida = boxMedi.split("-");
        System.out.println("Numero: " + RayMedida[0]);

        /*
        String cadena = boxMedi;
        char [] cadena_div = cadena.toCharArray();
        String n = "";
        for(int i = 0; i < cadena_div.length; i++){
            if(Character.isDigit(cadena_div[i])){
                n+=cadena_div[i];
            }
        }System.out.println("Numero: "+n);
        
        
         */
        if (nameMeasure.isEmpty()) {
            JOptionPane.showMessageDialog(this, "!!!Campos vacios por favor llenar registros.");
        } else {
            try ( Connection conexion = con.get_connection()) {
                try {
                    PreparedStatement ps = null;
                    String query = ("INSERT INTO product(name_product,id_measure)VALUES('" + nameMeasure + "'," + RayMedida[0] + ")");
                    ps = conexion.prepareStatement(query);
                    ps.executeUpdate();
                    showTableProduct();
                    txtNameProduct.setText("");

                    JOptionPane.showMessageDialog(this, "Guardado.");
                } catch (Exception e) {
                    System.err.print(e.toString());
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al guardar.");
                }
            } catch (SQLException e) {
                System.err.print(e.toString());
                JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado.\nFavor comunicarse con el administrador.");
            }
        }


    }//GEN-LAST:event_btGuardarProductActionPerformed

    private void boxMedidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxMedidaItemStateChanged
        // TODO add your handling code here:
        String boxMedi;
        boxMedi = boxMedida.getSelectedItem().toString();
        //*************
    }//GEN-LAST:event_boxMedidaItemStateChanged

    private void boxMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMedidaActionPerformed

    private void jMenuIProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIProductActionPerformed
        // TODO add your handling code here:
        actualizarProducto();
    }//GEN-LAST:event_jMenuIProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxMedida;
    private javax.swing.JButton btGuardarProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuIProduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tlProduct;
    private javax.swing.JTextPane txtNameProduct;
    // End of variables declaration//GEN-END:variables

    private void cargarMedida(JComboBox pp) {
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        pp.setModel(combo);
        CTMeasure ctc = new CTMeasure();

        try {
            Statement st = conexcion.createStatement();
            ResultSet rr = st.executeQuery("SELECT * FROM measure");

            while (rr.next()) {
                measure con = new measure();
                System.out.println(rr.getString(1));
                con.setId_measure(rr.getInt(1));
                con.setName_measure(rr.getString(2));
                ctc.AgregarMeasure(con);
                combo.addElement(con.getId_measure() + " - " + con.getName_measure());
                System.out.println("Exito....");
            }

        } catch (Exception e) {
            System.out.println("Error, no se puede mostrar combo" + e);
        }
    }
}
