/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

    

import Controler.conexcion;
import java.sql.Connection;
import java.sql.PreparedStatement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Usserss extends javax.swing.JInternalFrame {

    conexcion con = new conexcion();
    Connection conexcion = con.get_connection();
    /**
     * Creates new form Usserss
     */
    public Usserss() {
        initComponents();
        showTableUser();
    }

    
    public void showTableUser(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Usuario");
        model.addColumn("Passwod");
        model.addColumn("Permisos");
        tbUser.setModel(model);
        
        String[] datos = new String[4];
        try {
            
            Statement leer = conexcion.createStatement();
            ResultSet rs = leer.executeQuery("SELECT * FROM usser");
            
            while (rs.next()) {

                System.out.println(rs.getString(1));
                System.out.println(rs.getString(2));
                System.out.println(rs.getString(3));
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                model.addRow(datos);
        
            }
            tbUser.setModel(model);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"error" + e.toString());
        }
    }
    
    
    
    public void ingresar() {

        conexcion db_connect = new conexcion();
        PreparedStatement ps = null;
        String User_name = txtNewUsuario.getText();
        String Passwordss = txtNewPass.getText();
        if (User_name.equals("") || Passwordss.equals("")) {
            JOptionPane.showMessageDialog(this, "Uno o mas campos estan vacios. Favor de llenarlos.");
        } else {
            try ( Connection conexion = db_connect.get_connection()) {
                try {
                    String query = "INSERT INTO usser(user_name,passwordss,permissions)VALUES(?,?,'Administrador')";
                    ps = conexion.prepareStatement(query);
                    ps.setString(1, txtNewUsuario.getText());
                    ps.setString(2, txtNewPass.getText());
                    ps.executeUpdate();
                    System.out.println("usuario creado");
                    this.dispose();
                    /*new Systemm().setVisible(true);*/
                    JOptionPane.showMessageDialog(this, "Usuario Creado Exitosamente.");

                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            } catch (SQLException e) {
                System.err.print(e.toString());
                JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado.\nFavor comunicarse con el administrador.");
            }
        }

    }
    
    public void actualizarUser() {
        int fila = tbUser.getSelectedRow();
        System.out.println(fila);

        int idUser = Integer.parseInt(this.tbUser.getValueAt(fila, 0).toString());
        String nameUser = tbUser.getValueAt(fila, 1).toString();
        String pass = tbUser.getValueAt(fila, 2).toString();

        System.out.println("La cantidad es: " + nameUser);
        System.out.println("El precio es : " + pass);

        try {
            PreparedStatement actu = conexcion.prepareStatement("UPDATE usser SET user_name ='" + nameUser + "', passwordss='" + pass + "' WHERE ID_USER = " + idUser + "");
            actu.executeUpdate();
            showTableUser();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error" + e.toString());

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuActuUser = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUser = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNewUsuario = new javax.swing.JTextField();
        btCrearUsuario = new javax.swing.JButton();
        txtNewPass = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();

        jMenuActuUser.setText("Actualizar Usuario");
        jMenuActuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActuUserActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuActuUser);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Usuarios");
        setPreferredSize(new java.awt.Dimension(1047, 593));

        tbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbUser.setComponentPopupMenu(jPopupMenu1);
        tbUser.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jScrollPane1.setViewportView(tbUser);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jLabel1.setText("Nobre del nuevo Usuario :");

        jLabel2.setText("Password ");

        txtNewUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewUsuarioKeyTyped(evt);
            }
        });

        btCrearUsuario.setText("Crear");
        btCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCrearUsuarioMouseClicked(evt);
            }
        });
        btCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearUsuarioActionPerformed(evt);
            }
        });

        txtNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewPassKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(txtNewUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(btCrearUsuario)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNewUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCrearUsuario))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewUsuarioKeyTyped
        // TODO add your handling code here:
        if (txtNewUsuario.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNewUsuarioKeyTyped

    private void btCrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCrearUsuarioMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btCrearUsuarioMouseClicked

    private void btCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearUsuarioActionPerformed
        // TODO add your handling code here:
        ingresar();
    }//GEN-LAST:event_btCrearUsuarioActionPerformed

    private void txtNewPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPassKeyTyped
        // TODO add your handling code here:
        if (txtNewPass.getText().length() == 25) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNewPassKeyTyped

    private void jMenuActuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActuUserActionPerformed
        // TODO add your handling code here:
        actualizarUser();
    }//GEN-LAST:event_jMenuActuUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrearUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuActuUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbUser;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JTextField txtNewUsuario;
    // End of variables declaration//GEN-END:variables
}
